import express from "express";
import path from "path";
import bodyParser from "body-parser";
import cookieParser from "cookie-parser";
import compress from "compression";
import cors from "cors";
import helmet from "helmet";

import UserRoutes from "./routes/user.routes";
import authRoutes from "./routes/auth.routes";
import mediaRoutes from "./routes/media.routes";

const CURRENT_WORKING_DIR = process.cwd();

const app = express();

//app.use('/dist', express.static(path.join(CURRENT_WORKING_DIR, 'dist')))

const whitelist = ["http://localhost:3000"];
const corsOptions = {
  origin: function (origin, callback) {
    if (!origin || whitelist.indexOf(origin) !== -1) {
      callback(null, true);
    } else {
      callback(new Error("Not allowed by CORS"));
    }
  },
  credentials: true,
};

app.use(bodyParser.json());
app.use(cors(corsOptions));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(compress());
app.use(helmet());

app.use("/", UserRoutes);
app.use("/", authRoutes);
app.use("/", mediaRoutes);

app.get("/", (req, res) => {
  res.status(200).send({ data: "Success Media" });
});

// catching auth related errors generated by express-jwt

app.use((err, req, res, next) => {
  if (err.name === "UnauthorizedError") {
    res.status(401).json({ error: err.name + ": " + err.message });
  } else if (err) {
    res.status(400).json({ error: err.name + ": " + err.message });
    console.log(err);
  }
});

export default app;
